opt=-O3
path_to_eigen=
path_to_gsl_lib =$(shell /home/dunanqiao/software/gsl-2.6/gsl-finish/bin/gsl-config --libs)
path_to_gsl_include = $(shell /home/dunanqiao/software/gsl-2.6/gsl-finish/bin/gsl-config --cflags)
cppstd=-std=c++11
