# compiler and FLAGS
CC = g++ 
FC = gfortran 
CXXFLAGS = -std=c++11 -O3 -march=native
FFLAGS = -O3 -march=native

# library path
EIGEN_INC = -I/home/dunanqiao/software/eigen-3.3.9
GSL_LIB = $(shell gsl-config --libs)
GSL_INC = $(shell gsl-config --cflags)

